name: Node CI

on: [push, pull_request]

jobs:
  prepare_version:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Prepare version
      run: |
        # does prepare the version, but not commit it
        node ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir
    - uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  build_and_test_linux:
    name: "Build & Test (Linux)"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: npm build and test
      run: |
        head package.json
        ls -al
        npm run build
        npm test

        # TODO: save artifacts for webapp
