name: Node CI

on: [push]

jobs:
  prepare_version:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install npm dependencies
      run: |
        npm ci
        # ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Prepare version
      run: |
        # does prepare the version, but not commit it
        ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir
    - uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  lint_linux:
    name: "Lint sources"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install npm dependencies
      run: |
        cat package.json
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - run: npm run lint

  build_and_test_linux:
    name: "Build & Test (Linux)"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install npm dependencies
      run: |
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Build the web app 
      run: |
        head package.json
        ls -al
        npm run build

    - name: Run the tests
      run: npm test

    - name: Bundle web
      run: | 
        mkdir -p dist_web/dist/web
        cp index.html dist_web/index.html
        cp -r dist/web dist_web/dist
        mkdir -p dist_web/src/resources
        cp -r src/resources dist_web/src
        cp favicon.ico dist_web/

    - uses: actions/upload-artifact@master
      with:
        name: dist_web
        path: dist_web

  build_and_test_macos:
    name: "Build & Test (macOS)"
    needs: prepare_version
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        cat package.json
        npm install -g npm
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: Build the Electron app
      run: npm run electron-build-macos
      env: 
        CSC_LINK: ${{ secrets.CSC_LINK }}

    - name: Prepare macOS Bundle
      run: |
        mkdir dist_electron_macos
        cp dist/electron/bpmn-studio-setup**.zip dist_electron_macos
        cp dist/electron/bpmn-studio-setup**.dmg dist_electron_macos

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_macos
        path: dist_electron_macos

  build_and_test_windows:
    name: "Build & Test (Windows)"
    needs: prepare_version
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
      shell: powershell

    - name: Install Windows build tools
      run: npm --vs2015 install --global windows-build-tools
      shell: powershell

    - name: Build the Electron app
      run: npm run electron-build-windows

    - name: Run the tests
      run: npm test

    - name: Prepare Windows Bundle
      run: |
        mkdir dist_electron_windows
        copy-item .\dist\electron\bpmn-studio-setup-**.exe .\dist_electron_windows\
      shell: powershell

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_windows
        path: dist_electron_windows

  prepare_and_tag_version:
    name: "Commit & Tag Version"
    needs: [build_and_test_linux, build_and_test_macos, build_and_test_windows]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
      
    - name: Commit and Tag
      run: |
        echo ${GITHUB_REF##*/}
        ./node_modules/.bin/ci_tools commit-and-tag-version --only-on-primary-branches
        ./node_modules/.bin/ci_tools update-github-release --only-on-primary-branches --use-title-and-text-from-git-tag
      env: 
        GH_USER: ${{ github.actor }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #GIT_BRANCH: ${GITHUB_REF##*/}

  publish_npm:
    name: "Publish npm package"
    needs: prepare_and_tag_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: npm ci

    - name: Publish npm package
      run: node ./node_modules/.bin/ci_tools publish-npm-package --create-tag-from-branch-name
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
