name: Node CI

on: [push, pull_request]

jobs:
  prepare_version:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only @process-engine/ @essential-projects/
    - name: Prepare version
      run: |
        # does prepare the version, but not commit it
        node ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir

  build_and_test:
    needs: prepare_version
    runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     node: [10]
    #     os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
    - uses: actions/checkout@master
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only @process-engine/ @essential-projects/
    - name: npm build and test
      run: |
        npm run build
        npm test
