name: Node CI

on: [push, pull_request]

jobs:
  prepare_version:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM dependencies
      run: |
        npm ci
        # node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Prepare version
      run: |
        # does prepare the version, but not commit it
        node ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir
    - uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  lint_linux:
    name: "Lint sources"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        cat package.json
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - run: npm run lint

  build_and_test_linux:
    name: "Build & Test (Linux)"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: npm build and test
      run: |
        head package.json
        ls -al
        npm run build
        npm test

        # TODO: save artifacts for webapp

  build_and_test_macos:
    name: "Build & Test (macOS)"
    needs: prepare_version
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        cat package.json
        npm install -g npm
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: npm build and test
      run: |
        npm run electron-build-macos

        npm run test-electron

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_macos
        path: dist/electron

  build_and_test_windows:
    name: "Build & Test (Windows)"
    needs: prepare_version
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: Install Windows build tools
      run: npm install --global windows-build-tools
      shell: powershell

    - name: npm build and test
      run: |
        npm run electron-build-windows

        npm run test-electron

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_windows
        path: dist/electron
