name: Node CI

on: [push]

jobs:
  prepare_version:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM dependencies
      run: |
        npm ci
        # node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Prepare version
      run: |
        # does prepare the version, but not commit it
        node ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir
    - uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  lint_linux:
    name: "Lint sources"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        cat package.json
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - run: npm run lint

  build_and_test_linux:
    name: "Build & Test (Linux)"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/
    - name: Build the web app 
      run: |
        head package.json
        ls -al
        npm run build

    - name: Run the tests
      run: npm test

    - name: Bundle web
      run: | 
        mkdir -p dist_web/dist/web
        cp index.html dist_web/index.html
        cp -r dist/web dist_web/dist

    - uses: actions/upload-artifact@master
      with:
        name: dist_web
        path: dist_web

  build_and_test_macos:
    name: "Build & Test (macOS)"
    needs: prepare_version
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        cat package.json
        npm install -g npm
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: Build the Electron app
      run: npm run electron-build-macos
      env: 
        CSC_LINK: ${{ secrets.CSC_LINK }}

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_macos
        path: dist/electron

  build_and_test_windows:
    name: "Build & Test (Windows)"
    needs: prepare_version
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."
    - name: Install NPM dependencies
      run: |
        npm ci
        node ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: Install Windows build tools
      run: npm --vs2015 install --global windows-build-tools
      shell: powershell

    - name: Build the Electron app
      run: npm run electron-build-windows

    - name: Run the tests
      run: npm test

    - uses: actions/upload-artifact@master
      with:
        name: dist_electron_windows
        path: dist/electron
